const REPLACEMENTS: Array<[RegExp, string]> = [
  [/Ã¡/g, "á"],
  [/Ã©/g, "é"],
  [/Ã­/g, "í"],
  [/Ã³/g, "ó"],
  [/Ãº/g, "ú"],
  [/Ã±/g, "ñ"],
  [/Ã/g, "Á"],
  [/Ã‰/g, "É"],
  [/Ã/g, "Í"],
  [/Ã“/g, "Ó"],
  [/Ãš/g, "Ú"],
  [/Ã‘/g, "Ñ"],
  [/Â¿/g, "¿"],
  [/Â¡/g, "¡"],
  [/Â·/g, "·"],
  [/â€”/g, "—"],
  [/â€“/g, "–"],
  [/â†’/g, "→"],
  [/S\?bado/g, "Sábado"],
  [/s\?bado/g, "sábado"],
  [/Mi\?rcoles/g, "Miércoles"],
  [/mi\?rcoles/g, "miércoles"],
  [/Miercoles/g, "Miércoles"],
  [/miercoles/g, "miércoles"],
  [/Sabado/g, "Sábado"],
  [/sabado/g, "sábado"],
  [/A\?o/g, "Año"],
  [/a\?o/g, "año"],
  [/N\?mero/g, "Número"],
  [/n\?mero/g, "número"],
  [/Sesi\?n/g, "Sesión"],
  [/sesi\?n/g, "sesión"],
  [/Observaci\?n/g, "Observación"],
  [/observaci\?n/g, "observación"],
  [/Evaluaci\?n/g, "Evaluación"],
  [/evaluaci\?n/g, "evaluación"],
  [/Gesti\?n/g, "Gestión"],
  [/gesti\?n/g, "gestión"],
  [/Informaci\?n/g, "Información"],
  [/informaci\?n/g, "información"],
  [/Atenci\?n/g, "Atención"],
  [/atenci\?n/g, "atención"],
  [/Pr\?xima/g, "Próxima"],
  [/pr\?xima/g, "próxima"],
  [/P\?gina/g, "Página"],
  [/p\?gina/g, "página"],
  [/T\?tulo/g, "Título"],
  [/t\?tulo/g, "título"],
  [/V\?lidos/g, "Válidos"],
  [/v\?lidos/g, "válidos"],
  [/M\?nimo/g, "Mínimo"],
  [/m\?nimo/g, "mínimo"],
  [/M\?ximo/g, "Máximo"],
  [/m\?ximo/g, "máximo"],
  [/N\?mina/g, "Nómina"],
  [/n\?mina/g, "nómina"],
  [/Acci\?n/g, "Acción"],
  [/acci\?n/g, "acción"],
  [/academica/g, "académica"],
  [/Academica/g, "Académica"],
  [/academico/g, "académico"],
  [/Academico/g, "Académico"],
];

export function normalizarTextoVisible(value: string | null | undefined): string {
  if (!value) return "";

  return REPLACEMENTS.reduce(
    (text, [pattern, replacement]) => text.replace(pattern, replacement),
    value,
  );
}
